#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AllowedAlgorithm {
    BinarySearch,
    BinarySearchOnAnswer,
    TwoPointers,
    SlidingWindow,
    PrefixSum,
    Sorting,
    Bfs,
    Dfs,
    TopologicalSort,
    Dsu,
    Dijkstra,
    Mst,
    FenwickTree,
    SegmentTree,
    SparseTable,
    MonotonicStack,
    MonotonicQueue,
    BinaryLifting,
    Lca,
    TreeDp,
    BitmaskDp,
    Sieve,
    Kmp,
    ZAlgorithm,
    RollingHash,
    Trie,
}

impl AllowedAlgorithm {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::BinarySearch => "Binary Search",
            Self::BinarySearchOnAnswer => "Binary Search on Answer",
            Self::TwoPointers => "Two Pointers",
            Self::SlidingWindow => "Sliding Window",
            Self::PrefixSum => "Prefix Sum",
            Self::Sorting => "Sorting",
            Self::Bfs => "BFS",
            Self::Dfs => "DFS",
            Self::TopologicalSort => "Topological Sort",
            Self::Dsu => "DSU",
            Self::Dijkstra => "Dijkstra",
            Self::Mst => "MST",
            Self::FenwickTree => "Fenwick Tree",
            Self::SegmentTree => "Segment Tree",
            Self::SparseTable => "Sparse Table",
            Self::MonotonicStack => "Monotonic Stack",
            Self::MonotonicQueue => "Monotonic Queue",
            Self::BinaryLifting => "Binary Lifting",
            Self::Lca => "LCA",
            Self::TreeDp => "Tree DP",
            Self::BitmaskDp => "Bitmask DP",
            Self::Sieve => "Sieve",
            Self::Kmp => "KMP",
            Self::ZAlgorithm => "Z Algorithm",
            Self::RollingHash => "Rolling Hash",
            Self::Trie => "Trie",
        }
    }
}
